### ISSUE TITLE
Cannot send a content-body with this verb-type

### ISSUE THREAD

**Issue by Peryslaw81** [romabliski/PayU-CSharp-Client#12]
w czasie budowania requestu dla GET body powinno być zawsze puste, obecnie jeśli content będzie puste to i tak pusty obiekt json powstanie w content
brak możliwości np sprawdzenia statusu zamówienia
błąd z tematu jest wyrzucany

przykład takiego HttpRequestMessage:

 {Method: GET, RequestUri: 'https://secure.snd.payu.com/api/v2_1/orders/4K4JXHPLGS201030ubhbd6zdP01', Version: 1.1, Content: PayU.Client.Models.Content.JsonContent, Headers:
{
  Authorization: bearer d483c6bc-afc1-4c7c-aaae-98c73c60d468
  Accept: application/json
  Content-Type: application/json
}}
 

PayuClientRequestBuilder  l:26
 public static HttpRequestMessage BuildRequestMessage(Uri url, HttpMethod method, string token, object content)

StackTrace

This exception was originally thrown at this call stack:
    [External Code]
    PayU.Client.PayUApiHttpCommunicator<T>.SendReceiveAsync(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpClient, System.Threading.CancellationToken) in PayUApiHttpCommunicator.cs
    [External Code]
    PayU.Client.PayUApiHttpCommunicator<T>.SendRequestByClientAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) in PayUApiHttpCommunicator.cs
    [External Code]
    PayU.Client.PayUApiHttpCommunicator<T>.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) in PayUApiHttpCommunicator.cs
    [External Code]
    PayU.Client.BaseClient.ProcessAsync<T>(System.Uri, System.Net.Http.HttpMethod, System.Threading.CancellationToken, object, PayU.Client.TrustedMerchant) in BaseClient.cs
    [External Code]
    PayU.Client.PayUClient.GetOrderAsync(string, System.Threading.CancellationToken) in PayUClient.cs
    ...
    [Call Stack Truncated]

**Comment by jakroma** [comment]
Poprawione w wersji 1.1.1. Sorry za zapłon ale nie sądziłem że ktoś będzie tego używał. A zrobiłem to na własny użytek.
